mod commands;
pub mod debug;
mod error;
mod models;
mod services;
mod setup;
mod state;
mod window_watchdog;

/// Generated tweak data compiled from YAML files at build time.
/// This module is auto-generated by build.rs - do not edit manually.
mod generated_tweaks {
    include!(concat!(env!("OUT_DIR"), "/generated_tweaks.rs"));
}

pub use debug::{emit_debug_log, is_debug_enabled, set_debug_enabled, DebugLevel, DebugLogEntry};
pub use error::Error;
pub use models::*;
use state::AppState;
use tauri_plugin_log::{Target, TargetKind};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_prevent_default::debug())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_process::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .targets([
                    // Log to console in debug builds only
                    Target::new(TargetKind::Stdout),
                    // Log to webview console for frontend debugging
                    Target::new(TargetKind::Webview),
                ])
                // In debug mode: show debug level and above
                // In release mode: show warn level and above
                .level(if cfg!(debug_assertions) {
                    log::LevelFilter::Debug
                } else {
                    log::LevelFilter::Warn
                })
                // More verbose for our own crate
                .level_for(
                    "app_lib",
                    if cfg!(debug_assertions) {
                        log::LevelFilter::Trace
                    } else {
                        log::LevelFilter::Info
                    },
                )
                // Use colored output format with ANSI colors
                .format(|out, message, record| {
                    // Color codes for different log levels
                    let color = match record.level() {
                        log::Level::Error => "\x1b[31m", // Red
                        log::Level::Warn => "\x1b[33m",  // Yellow
                        log::Level::Info => "\x1b[32m",  // Green
                        log::Level::Debug => "\x1b[36m", // Cyan
                        log::Level::Trace => "\x1b[35m", // Magenta
                    };
                    let reset = "\x1b[0m";

                    out.finish(format_args!(
                        "{}[{}][{}]{}[{}] {}",
                        color,
                        chrono::Local::now().format("%Y-%m-%d][%H:%M:%S"),
                        record.target(),
                        reset,
                        record.level(),
                        message
                    ))
                })
                .build(),
        )
        .manage(AppState(Default::default()))
        .setup(|app| {
            log::info!("Application starting...");
            log::debug!("Debug logging enabled");

            // Start window visibility watchdog
            // If window isn't shown within 10 seconds, force show it
            // This prevents the app from getting stuck hidden if frontend fails to mount
            let app_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                window_watchdog::start_window_watchdog(app_handle, "main", 10).await;
            });

            setup::setup(app)
        })
        .invoke_handler(tauri::generate_handler![
            commands::general::show_main_window,
            commands::system::get_system_info,
            // Tweak query commands
            commands::tweaks::query::get_categories,
            commands::tweaks::query::get_available_tweaks,
            commands::tweaks::query::get_available_tweaks_for_version,
            commands::tweaks::query::get_tweaks_by_category,
            commands::tweaks::query::get_tweak,
            commands::tweaks::query::get_tweak_status,
            commands::tweaks::query::get_all_tweak_statuses,
            commands::tweaks::query::get_tweak_inspection,
            // Tweak apply commands
            commands::tweaks::apply::apply_tweak,
            commands::tweaks::apply::revert_tweak,
            // Tweak batch commands
            commands::tweaks::batch::batch_apply_tweaks,
            commands::tweaks::batch::batch_revert_tweaks,
            commands::debug::set_debug_mode,
            commands::debug::get_debug_mode,
            // Backup commands
            commands::backup::has_backup,
            commands::backup::list_backups,
            commands::backup::get_backup_info,
            commands::backup::get_backup_system_status,
            commands::backup::cleanup_old_backups,
            commands::backup::validate_snapshots,
            // Profile commands
            commands::profile::profile_export,
            commands::profile::profile_import,
            commands::profile::profile_validate,
            commands::profile::profile_apply,
            commands::profile::get_windows_version,
            commands::profile::get_saved_profiles,
            commands::profile::delete_saved_profile,
            // Elevation commands
            commands::elevation::apply_registry_as_system,
            commands::elevation::delete_registry_as_system,
            commands::elevation::can_use_system_elevation,
            commands::elevation::restart_as_admin,
            // Update commands
            commands::update::check_for_update,
            commands::update::install_update,
        ])
        .run(tauri::generate_context!())
        .unwrap_or_else(|e| {
            log::error!("Failed to run Tauri application: {:?}", e);
            std::process::exit(1);
        });
}
