mod commands;
pub mod debug;
mod error;
#[cfg(feature = "test-build")]
mod manual_tests;
mod models;
mod services;
mod setup;
pub mod tweaks;
mod window_watchdog;

/// The build-time-compiled tweak corpus (`tweaks/*.yaml`, spec §11). Auto-generated by
/// `build.rs` — do not edit manually. `tweaks::compiled_corpus()` is the accessor.
mod generated_corpus {
    include!(concat!(env!("OUT_DIR"), "/generated_corpus.rs"));
}

pub use debug::{emit_debug_log, is_debug_enabled, set_debug_enabled, DebugLevel, DebugLogEntry};
pub use error::Error;
pub use models::*;
use tauri_plugin_log::{RotationStrategy, Target, TargetKind};

#[derive(Debug, PartialEq)]
enum Launch<'a> {
    Gui,
    Broker {
        req: &'a str,
        resp: &'a str,
        identity: &'a str,
    },
    MalformedBroker,
}

// Only argv[1], where `run_elevated_broker` puts it; a later `--broker` is a GUI arg, and the GUI ignores args.
fn classify_launch(args: &[std::ffi::OsString]) -> Launch<'_> {
    match args {
        [_, flag, rest @ ..] if flag == "--broker" => match rest {
            [req, resp, identity] => match (req.to_str(), resp.to_str(), identity.to_str()) {
                (Some(req), Some(resp), Some(identity)) => Launch::Broker {
                    req,
                    resp,
                    identity,
                },
                _ => Launch::MalformedBroker,
            },
            _ => Launch::MalformedBroker,
        },
        _ => Launch::Gui,
    }
}

/// `Some(exit code)` when launched as the broker, `None` to start the GUI. Call before any Tauri init.
pub fn run_broker_if_requested() -> Option<i32> {
    let args: Vec<std::ffi::OsString> = std::env::args_os().collect();
    match classify_launch(&args) {
        Launch::Gui => None,
        Launch::Broker {
            req,
            resp,
            identity,
        } => Some(services::elevation::run_broker(req, resp, identity)),
        Launch::MalformedBroker => Some(services::elevation::malformed_argv_exit_code()),
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    use services::single_instance::{self, Instance};
    let after_restart = std::env::args_os()
        .nth(1)
        .is_some_and(|a| a == single_instance::AFTER_RESTART_ARG);
    let mut instance = match single_instance::acquire(after_restart) {
        Instance::First(guard) => guard,
        Instance::AlreadyRunning => {
            single_instance::focus_running_instance("MagicX Toolbox");
            return;
        }
    };
    let instance_note = instance.take_note();
    tauri::Builder::default()
        // Closing mid-apply kills the process while an elevated child may still be driving, and
        // leaves the snapshot entry that was written before the first drive with nothing to undo
        // it. Refuse, and say so, rather than losing the tweak halfway.
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                if !crate::tweaks::engine::lifecycle::gate().commit_close() {
                    api.prevent_close();
                    log::warn!("close refused: an apply is still in flight");
                    use tauri::Emitter;
                    let _ = window.emit(
                        "close-blocked",
                        "A tweak is still being changed. Close the window again once it finishes.",
                    );
                }
            }
        })
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_prevent_default::debug())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_process::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .targets([
                    Target::new(TargetKind::Stdout),
                    Target::new(TargetKind::Webview),
                    // The only record that outlives the session. Never log the broker command
                    // line: it carries the request and response temp paths.
                    Target::new(TargetKind::LogDir {
                        file_name: Some("magicx-toolbox".into()),
                    }),
                ])
                // Not the default KeepOne: it deletes the only file at 40,000 bytes.
                // KeepSome(n) keeps n archives plus the active file: 5 x 2 MiB = 10 MiB cap.
                .max_file_size(2 * 1024 * 1024)
                .rotation_strategy(RotationStrategy::KeepSome(4))
                .level(if cfg!(debug_assertions) {
                    log::LevelFilter::Debug
                } else {
                    log::LevelFilter::Warn
                })
                // More verbose for our own crate
                .level_for(
                    "app_lib",
                    if cfg!(debug_assertions) {
                        log::LevelFilter::Trace
                    } else {
                        log::LevelFilter::Info
                    },
                )
                // Use colored output format with ANSI colors
                .format(|out, message, record| {
                    // Color codes for different log levels
                    let color = match record.level() {
                        log::Level::Error => "\x1b[31m", // Red
                        log::Level::Warn => "\x1b[33m",  // Yellow
                        log::Level::Info => "\x1b[32m",  // Green
                        log::Level::Debug => "\x1b[36m", // Cyan
                        log::Level::Trace => "\x1b[35m", // Magenta
                    };
                    let reset = "\x1b[0m";

                    out.finish(format_args!(
                        "{}[{}][{}]{}[{}] {}",
                        color,
                        chrono::Local::now().format("%Y-%m-%d][%H:%M:%S"),
                        record.target(),
                        reset,
                        record.level(),
                        message
                    ))
                })
                .build(),
        )
        .setup(move |app| {
            log::info!("Application starting...");
            if let Some(note) = instance_note {
                log::warn!("{note}");
            }
            log::debug!("Debug logging enabled");

            // Start window visibility watchdog.
            // Dev startup can be slower (tooling, first-load optimization), so use a longer
            // timeout in debug builds to avoid false fallback logs.
            let app_handle = app.handle().clone();
            let watchdog_timeout_secs = if cfg!(debug_assertions) { 30 } else { 10 };
            tauri::async_runtime::spawn(async move {
                window_watchdog::start_window_watchdog(app_handle, "main", watchdog_timeout_secs)
                    .await;
            });

            setup::setup(app)
        })
        .invoke_handler(tauri::generate_handler![
            commands::general::show_main_window,
            commands::system::get_system_info,
            commands::debug::set_debug_mode,
            commands::tweaks::get_tweaks,
            commands::tweaks::get_categories,
            commands::tweaks::get_statuses_stream,
            commands::tweaks::apply_tweak,
            commands::tweaks::restore_tweak,
            commands::tweaks::get_tweak_status,
            commands::tweaks::list_snapshot_entries,
            commands::tweaks::discard_snapshot_entry,
            commands::tweaks::keep_current_state,
            commands::tweaks::rescan_after_elevation,
            commands::tweaks::get_elevation_state,
            // Elevation commands
            commands::elevation::restart_as_admin,
            // Update commands
            commands::update::check_for_update,
            commands::update::install_update,
            commands::manual_tests::manual_tests_available,
            #[cfg(feature = "test-build")]
            commands::manual_tests::list_manual_tests,
            #[cfg(feature = "test-build")]
            commands::manual_tests::run_manual_test,
            #[cfg(feature = "test-build")]
            commands::manual_tests::cancel_manual_test,
        ])
        .run(tauri::generate_context!())
        .unwrap_or_else(|e| {
            log::error!("Failed to run Tauri application: {:?}", e);
            std::process::exit(1);
        });
}

#[cfg(test)]
mod tests {
    use super::{classify_launch, Launch};
    use std::ffi::OsString;

    fn argv(args: &[&str]) -> Vec<OsString> {
        args.iter().map(OsString::from).collect()
    }

    #[test]
    fn broker_mode_is_entered_only_from_argv1() {
        assert_eq!(
            classify_launch(&argv(&["app.exe", "--broker", "r.json", "s.json", "id"])),
            Launch::Broker {
                req: "r.json",
                resp: "s.json",
                identity: "id"
            }
        );
        assert_eq!(
            classify_launch(&argv(&[
                "app.exe", "x", "--broker", "r.json", "s.json", "id"
            ])),
            Launch::Gui
        );
    }

    #[test]
    fn a_launch_without_broker_opens_the_gui() {
        assert_eq!(classify_launch(&argv(&["app.exe"])), Launch::Gui);
        assert_eq!(classify_launch(&argv(&[])), Launch::Gui);
        assert_eq!(classify_launch(&argv(&["app.exe", "r.json"])), Launch::Gui);
    }

    #[test]
    fn a_malformed_broker_invocation_never_opens_the_gui() {
        for args in [
            &["app.exe", "--broker"][..],
            &["app.exe", "--broker", "r.json"],
            &["app.exe", "--broker", "r.json", "s.json"],
            &["app.exe", "--broker", "r.json", "s.json", "id", "extra"],
        ] {
            assert_eq!(
                classify_launch(&argv(args)),
                Launch::MalformedBroker,
                "{args:?}"
            );
        }
    }

    #[test]
    fn a_non_unicode_broker_path_is_malformed() {
        use std::os::windows::ffi::OsStringExt;
        let lone_surrogate = OsString::from_wide(&[0xD800]);
        let args = [
            OsString::from("app.exe"),
            OsString::from("--broker"),
            lone_surrogate,
            OsString::from("s.json"),
            OsString::from("id"),
        ];
        assert_eq!(classify_launch(&args), Launch::MalformedBroker);
    }
}
